name: SprintWand
main: org.hopto.seed419.SprintWand
version: 1.2
author: seed419
commands:
   sprint:
     description: Enables or disables SprintWand
   setwand:
     description: Sets the SprintWand to a new item  Parameters- New items ID
   wand:
     aliases: Prints the current SprintWand item to the user
